### ISSUE TITLE
can not find tx_uda.txt

### ISSUE THREAD

**Issue by promefire** [lxycopper/PLU#3]

**Comment by yellowflying2** [comment]
请问解决了吗

**Comment by yellowflying2** [comment]
> _No description provided._

请问解决了吗

**Comment by GZ-Metal-Cell** [comment]
请问解决了吗

**Comment by promefire** [comment]
没有

**Comment by lxycopper** [comment]
Thanks for your question. You may refer to this reply https://github.com/lxycopper/PLU/issues/1#issuecomment-2294877996
